--- 
 - name: Adding linux user
   user: 
     name: "{{ item.username }}"
     comment: "{{ item.username }}@github"
     shell: /bin/bash
     state: "{{ item.state | default('present') }}"
   with_items:
     users_list
 - name: creating .ssh directory
   file: 
    path: /home/{{ item.username}}/.ssh
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0700
   with_items:
     users_list  
 - name: Assinging sudo rules to users
   copy:
     content: "{{ item.username }} ALL=(ALL) NOPASSWD:ALL" 
     dest: /etc/sudoers.d/99-{{ item.username }}
     mode: 0440
   when: item.type is defined and item.type == 'admin' and item.get('state', 'present') == 'present'
   with_items:
     users_list
 - name: Adding ssh keys from github
   get_url:
     url: https://github.com/{{ item.github_username }}.keys
     dest: /home/{{ item.username }}/.ssh/authorized_keys
     owner: "{{ item.username }}"
     group: "{{ item.username }}"
     mode: 0600
   when: item.get('state', 'present') == 'present'
   with_items:
     users_list
 
